name: Build and Release Binary

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build binary
      run: |
        python build_binary.py
        
    - name: Upload binary as artifact
      uses: actions/upload-artifact@v3
      with:
        name: update-noti-binary
        path: |
          dist/update-noti
          dist/release-info.json
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.version || github.ref_name }}
        name: Package Updates Notifier ${{ github.event.inputs.version || github.ref_name }}
        body: |
          ## 📦 Package Updates Notifier Release
          
          ### 🚀 Installation
          ```bash
          curl -fsSL https://raw.githubusercontent.com/${{ github.repository }}/main/install.sh | sudo bash
          ```
          
          ### 📋 What's Included
          - ✅ Standalone binary (`update-noti`) - No Python required!
          - ✅ Auto-installer with systemd + cron scheduling
          - ✅ Self-updating capability
          - ✅ Multi-package manager support (apt, dnf, yum, pacman, zypper)
          - ✅ Slack integration with beautiful formatting
          - ✅ System information reporting
          
          ### 💻 System Requirements
          - Linux x64 (Ubuntu, Debian, RHEL, CentOS, Fedora, Arch, openSUSE)
          - No Python installation required (standalone binary)
          - Internet connectivity for updates and Slack notifications
          
          ### 🔧 Configuration
          After installation, configure your packages in `/opt/update-noti/config.json`:
          ```json
          {
            "auto_update": ["tailscale", "netdata", "nginx"],
            "slack_webhook": "https://hooks.slack.com/services/YOUR/WEBHOOK/URL"
          }
          ```
          
          ### 📊 Binary Information
          - Size: ~8-10 MB (standalone, no dependencies)
          - Built with PyInstaller on Ubuntu Latest
          - Tested on major Linux distributions
          
          ---
          **Full documentation:** https://github.com/${{ github.repository }}#readme
        files: |
          dist/update-noti
          dist/release-info.json
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}