name: Nightly Release

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  nightly:
    name: Build and Publish Nightly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true
      - name: Build linux/amd64
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 \
            go build -ldflags "-s -w -X main.Version=nightly-${{ github.sha }}" \
            -o update-noti_linux_amd64 ./cmd/update-noti
      - name: Build linux/arm64
        run: |
          GOOS=linux GOARCH=arm64 CGO_ENABLED=0 \
            go build -ldflags "-s -w -X main.Version=nightly-${{ github.sha }}" \
            -o update-noti_linux_arm64 ./cmd/update-noti
      - name: Generate checksums
        run: sha256sum update-noti_linux_* > checksums.txt
      - name: Publish/Update Nightly Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly
          name: Nightly
          body: |
            Nightly build for commit ${{ github.sha }}.

            Artifacts:
            - update-noti_linux_amd64
            - update-noti_linux_arm64
            - checksums.txt
          files: |
            update-noti_linux_amd64
            update-noti_linux_arm64
            checksums.txt
          prerelease: true
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
